- name: Build Apache+PHP image
  community.docker.docker_image:
    name: "apachephp"
    build:
      path: "{{ role_path }}/files"
      dockerfile: Dockerfile.apachephp
    source: build

- name: Build MySQL image
  community.docker.docker_image:
    name: "mysql-custom"
    build:
      path: "{{ role_path }}/files"
      dockerfile: Dockerfile.mysql
    source: build

